title:              Poyi Chen

# Versioning
current_version: 1.5.0
foundation_version: 6.0.0

author:
  name:             Poyi
  email:            poyi.design@gmail.com
  github:           poyi
  twitter:          poyichen

# Dependencies
markdown:           kramdown
#Syntax Highlighter
#highlighter:        pygments

# Permalinks
permalink:          pretty

# Server
source:             ./source
destination:        ./static

port:               9002
baseurl:            ""
url:                http://poyichen.com

# exclude this stuff when building the static site
exclude:            [
                      '.gitignore',
                      'README.md',
                      'Gemfile',
                      'Gemfile.lock',
                    ]

## CUSTOM VARS

#ga_id:             ##-########-###
site_name:          Poyi chen
site_description :  Portfolio site
site_copyright:     Copyright (c) 2016 @poyichen
site_url:           http://www.poyichen.com
site_email:         poyi.design@gmail.com
site_phone:         (555) 555-1234



# Assets
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          ./assets/stylesheets
  style:            :compressed
